### ISSUE TITLE
"export 'registerPlugin' was not found in '@capacitor/core'

### ISSUE THREAD

**Issue by luisurruela** [transistorsoft/capacitor-background-geolocation#12]
## Your Environment
* Plugin version: 4.2.0
* Platform: Android
* Device OS version: 11
* Device manufacturer / model: Motorola G9
* XCode version:
* Capacitor info
Installed Dependencies:

  @capacitor/core 2.4.1
  @capacitor/android 2.4.1
  @capacitor/cli 2.4.1
  @capacitor/ios 2.4.1
  @capacitor/electron not installed

## Expected Behavior
Successful build

## Actual Behavior
Error: ./node_modules/@transistorsoft/capacitor-background-geolocation/dist/index.js 38:19-33
"export 'registerPlugin' was not found in '@capacitor/core'

## Context
I think the problem is that I'm using Capacitor Core 2.4. I think this plugin needs capacitor 3. But, what version should I use to make it work with capacitor 2.4? 

</details>

**Comment by christocracy** [comment]
Only Capacitor 3 is supported.

**Comment by ronfak** [comment]
Unfortunately, Christocracy's philosophy is to refuse to write version compatibility requirements. I, for one, unfortunately discovered this after I had paid.

If you are using Capacitor 2 and for some reason can't or won't upgrade to Capacitor 3, you can try the Cordova version instead. It should work fine.

I was misled because it says that the plugin exists and has been tested for many years. But the truth is that the Capacitor version has only been around for 2 months or more. However I'm pretty confident that the code behind it is strong, because the native part has been around for years and is the same for all available variants...

**Comment by christocracy** [comment]
>Christocracy's philosophy is to refuse to write version compatibility requirement

It's not a policy.  A sentence in the README, such as *"Capacitor 3 required"*  will be pushed soon.

**Comment by christocracy** [comment]
[Capacitor 3+ required](https://github.com/transistorsoft/capacitor-background-geolocation#large_blue_diamond-installing-the-plugin)

![](https://dl.dropbox.com/s/6a0dt6ojdv0tfz0/Screen%20Shot%202021-08-17%20at%2010.16.10%20AM.png?dl=1)
