### ISSUE TITLE
Callback of onPowerSaveChange is not executed 

### ISSUE THREAD

**Issue by Tingyu-Sedimentum** [transistorsoft/capacitor-background-geolocation#147]
## Your Environment
* Plugin version:  
```
"@transistorsoft/capacitor-background-fetch": "^1.0.2",
"@transistorsoft/capacitor-background-geolocation": "^4.9.4",
```
* Platform: iOS 
* Device OS version: iOS 16.2  
* Device manufacturer / model: Apple iPhone XR  
* XCode version:
* Capacitor info (`npx cap doctor`) 
```
@capacitor/cli: 4.6.1
@capacitor/core: 4.6.1
@capacitor/ios: 4.6.1
@capacitor/android: 4.6.1
```
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->

      locationAuthorizationRequest: "Always",
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
      stopOnTerminate: false, // Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // Auto start tracking when device is powered-up.
      disableMotionActivityUpdates: true,
```

## Expected Behavior
If the app still in background, the `onPowerSaveChange` should be fired and the callback to send request should be executed when the phone goes to power save mode. 

## Actual Behavior
The callback is executed only when we turn on the power save mode shortly after the app goes to background. If the app stays in background for longer (more than a few minutes), probably becomes suspend mode, then the callback for `onPowerSaveChange` is not executed anymore. 

## Steps to Reproduce

N/A

## Context
I want to send a http request to our server when the phone goes to power-save mode. 
Is it possible to configure the plugin that it listens to the `onPowerSaveChange`? So that it sends request to the config url when the phone goes power save mode, like the geofence event. 

## Debug logs

N/A

**Comment by christocracy** [comment]
iOS doesn’t allow this event to fire your app is suspended in the background.  iOS would only fire this event in the background if your app is *not* suspended (ie where location-services are ON).  

You can tell the plugin to turn on location-services by calling .changePace(true).  After calling that *then* going to background, onPowerSaveChange *will* fire, since your app is not suspended in the background.

The plugin automatically calls .changePace(true) upon itself when the device is detected to be moving (see wiki “*Philosophy of Operation*”).

you are free to query the current state by calling [.isPowerSaveMode](https://transistorsoft.github.io/capacitor-background-geolocation/classes/backgroundgeolocation.html#ispowersavemode) whenever your app comes to the foreground.
