### ISSUE TITLE
why the notification configuration is missing from IOS?

### ISSUE THREAD

**Issue by shahabas-cp-14** [transistorsoft/capacitor-background-geolocation#155]
why the notification configuration is missing from IOS?

**Comment by christocracy** [comment]
The issue template (which you ignored) is **not** optional.  I have no idea what you're talking about.


## Your Environment
* Plugin version:
* Platform: iOS or Android
* Device OS version:
* Device manufacturer / model:
* XCode version:
* Capacitor info (`npx cap doctor`)
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by shahabas-cp-14** [comment]
Why In the IOS platform, background location configuration not contain notification settings?

**Comment by christocracy** [comment]
I don’t know what you’re talking about or what you’re expecting.  That’s the purpose of the issue template.
