### ISSUE TITLE
how to get a "DEBUG build"?

### ISSUE THREAD

**Issue by psy0rz** [transistorsoft/capacitor-background-geolocation#183]
I've tried everything, but i always get 
```
BackgroundGeolocation is fully functional in DEBUG builds without a license.
```

Using
```
    "@capacitor/geolocation": "^5.0.6",
    "@transistorsoft/capacitor-background-geolocation": "^5.0.0",
    "@capacitor/cli": "^5.0.0",


```

**Comment by christocracy** [comment]
It’s supposed to say that.  You’re also supposed to get a notification about it.

now go outside and move for a kilometre.

**Comment by loicparent** [comment]
Hello,
I'm trying the tool without licence for the moment. It works fine and better than the official Capacitor package but, after a minute approximately, the watcher stops working with a "wrong" sound. 

Is that normal and due to a limitation of the free version or is that a bug or something else?

_Thanks for your help,
Loïc_

**Comment by christocracy** [comment]
>Is that normal and due to a limitation of the free version or is that a bug or something else?

There are no limitations in DEGBUG builds.  I suggest you see the API Docs `Config.debug` to learn what that sound means.  You should also be observing the logs (See Wiki *Debugging*) via `$ adb logcat` to view the corresponding error message in the logs.

You **MUST** learn to observe the plugin's incredibly verbose logs.

**Comment by christocracy** [comment]
If you have further unrelated questsion / issues, post a new issue.
