### ISSUE TITLE
Feature request: Provide compass heading instead GPS derived heading

### ISSUE THREAD

**Issue by brian-g** [transistorsoft/capacitor-background-geolocation#94]
## Your Environment
* Plugin version: 4.4.4
* Platform: iOS and Android
* Device OS version: all
* Device manufacturer / model: all

## Expected Behavior
We expect that the heading returned by the plugin is derived from the device's compass (if present) and not from the GPS vector. In iOS, this is found in the CLHeading instance returned by the location manager delegate method `locationManager(_:didUpdateHeading:)`. I would assume that we would need to inform the background-geolocation plugin when we desired heading information. 

## Actual Behavior
The current plugin is using a compass heading that is derived from the GPS. This means that the heading is not a true heading of where the device is pointed and requires that the user moves a significant distance before it returns a value. 

## Steps to Reproduce

Not applicable, feature request. 

## Context

We want to provide our users with a true heading view of where they are in their agricultural fields so they can more easily return to the same location within the field.

**Comment by christocracy** [comment]
I've avoided using `locationManager(_:didUpdateHeading:)` for seven years because Android has nothing similar.  I've actually thought it surprising nobody has asked about this.

I've never had an issue with the GPS heading.

<img width="1368" alt="Screen Shot 2022-09-09 at 10 24 50 AM" src="https://user-images.githubusercontent.com/14999/189373053-1db78326-245d-445c-bd88-92058570d10a.png">

However, I have another user who wants to record locations only when the heading significantly changes, which would involve implementing [`headingFilter`](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620550-headingfilter?language=objc).

**Comment by brian-g** [comment]
I agree that the GPS-derived heading is accurate, as long as one is moving. 

I forgot to add to the context section, that our users would like to be able to turn and see the map update so they can start walking in the direction of the next point. They are not walking when they try to orient as they are in a field with growing crops.

**Comment by christocracy** [comment]
>I agree that the GPS-derived heading is accurate, as long as one is moving.

I suspect the same will be true for `locationManager(_:didUpdateHeading:)`, which may ultimately derive its information from the GPS heading.

Compass != heading.  Two locations are required to have a vector.

>our users would like to be able to turn and see the map update

Is this not compass you require?  Surely there's an existing Capacitor plugin that implements the magnetometer API.
